version: '3'
services:
  fs_controller:
    command: python3 -m fastchat.serve.controller --host 0.0.0.0
    build: .
    ports:
      - "21001:21001"
    environment:
      - FASTCHAT_MODEL_PATH=lmsys/vicuna-7b-v1.3
      - FASTCHAT_GPU_MEMORY=14Gib    
  model_worker:
    build: .
    command: python3 -m fastchat.serve.model_worker --model-path lmsys/vicuna-7b-v1.3 --device xpu --host 0.0.0.0 --max-gpu-memory '14Gib'
    ports:
      - "21002:21002"
    depends_on:
      - fs_controller
  gradio_web_server:
    build: .
    command: python3 -m fastchat.serve.gradio_web_server --host 0.0.0.0
    ports:
      - "7860:7860"
    depends_on:
      - fs_controller
      - model_worker
  openai_api_server:
    build: .
    command: python3 -m fastchat.serve.openai_api_server --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - fs_controller
      - model_worker